/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : bigint,
  'title' : string,
  'availableQuantity' : bigint,
  'isbn' : string,
  'yearPublished' : bigint,
  'author' : string,
  'genre' : string,
  'totalQuantity' : bigint,
}
export interface BorrowRecord {
  'id' : bigint,
  'memberId' : bigint,
  'borrowDate' : Time,
  'fineAmount' : bigint,
  'dueDate' : Time,
  'bookId' : bigint,
  'returnDate' : [] | [Time],
}
export interface DashboardStats {
  'totalFines' : bigint,
  'overdueLoans' : bigint,
  'mostBorrowedBooks' : Array<Book>,
  'totalBooks' : bigint,
  'totalMembers' : bigint,
  'recentlyAddedBooks' : Array<Book>,
  'activeLoans' : bigint,
}
export interface Member {
  'id' : bigint,
  'joinDate' : Time,
  'name' : string,
  'email' : string,
  'memberType' : { 'faculty' : null } |
    { 'student' : null } |
    { 'external' : null },
}
export interface Recommendation {
  'title' : string,
  'genreScore' : bigint,
  'bookId' : bigint,
  'author' : string,
  'genre' : string,
}
export type Time = bigint;
export interface UserProfile { 'memberId' : [] | [bigint], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBook' : ActorMethod<
    [string, string, string, string, bigint, bigint],
    bigint
  >,
  'addMember' : ActorMethod<
    [
      string,
      string,
      { 'faculty' : null } |
        { 'student' : null } |
        { 'external' : null },
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'borrowBook' : ActorMethod<[bigint, bigint], bigint>,
  'calculateFine' : ActorMethod<[bigint], bigint>,
  'getActiveBorrowRecords' : ActorMethod<[], Array<BorrowRecord>>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getBookBorrowHistory' : ActorMethod<[bigint], Array<BorrowRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMemberBorrowHistory' : ActorMethod<[bigint], Array<BorrowRecord>>,
  'getOverdueBorrowRecords' : ActorMethod<[], Array<BorrowRecord>>,
  'getRecommendations' : ActorMethod<[bigint], Array<Recommendation>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkPrincipalToMember' : ActorMethod<[bigint], undefined>,
  'removeBook' : ActorMethod<[bigint], undefined>,
  'removeMember' : ActorMethod<[bigint], undefined>,
  'returnBook' : ActorMethod<[bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBooksByAuthor' : ActorMethod<[string], Array<Book>>,
  'searchBooksByGenre' : ActorMethod<[string], Array<Book>>,
  'searchBooksByISBN' : ActorMethod<[string], Array<Book>>,
  'searchBooksByTitle' : ActorMethod<[string], Array<Book>>,
  'updateBook' : ActorMethod<
    [bigint, string, string, string, string, bigint, bigint],
    undefined
  >,
  'updateMember' : ActorMethod<
    [
      bigint,
      string,
      string,
      { 'faculty' : null } |
        { 'student' : null } |
        { 'external' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];