/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BorrowRecord = IDL.Record({
  'id' : IDL.Nat,
  'memberId' : IDL.Nat,
  'borrowDate' : Time,
  'fineAmount' : IDL.Nat,
  'dueDate' : Time,
  'bookId' : IDL.Nat,
  'returnDate' : IDL.Opt(Time),
});
export const Book = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'availableQuantity' : IDL.Nat,
  'isbn' : IDL.Text,
  'yearPublished' : IDL.Nat,
  'author' : IDL.Text,
  'genre' : IDL.Text,
  'totalQuantity' : IDL.Nat,
});
export const Member = IDL.Record({
  'id' : IDL.Nat,
  'joinDate' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'memberType' : IDL.Variant({
    'faculty' : IDL.Null,
    'student' : IDL.Null,
    'external' : IDL.Null,
  }),
});
export const UserProfile = IDL.Record({
  'memberId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalFines' : IDL.Nat,
  'overdueLoans' : IDL.Nat,
  'mostBorrowedBooks' : IDL.Vec(Book),
  'totalBooks' : IDL.Nat,
  'totalMembers' : IDL.Nat,
  'recentlyAddedBooks' : IDL.Vec(Book),
  'activeLoans' : IDL.Nat,
});
export const Recommendation = IDL.Record({
  'title' : IDL.Text,
  'genreScore' : IDL.Nat,
  'bookId' : IDL.Nat,
  'author' : IDL.Text,
  'genre' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addMember' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'faculty' : IDL.Null,
          'student' : IDL.Null,
          'external' : IDL.Null,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'borrowBook' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'calculateFine' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getActiveBorrowRecords' : IDL.Func([], [IDL.Vec(BorrowRecord)], ['query']),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getBookBorrowHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BorrowRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMemberBorrowHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BorrowRecord)],
      ['query'],
    ),
  'getOverdueBorrowRecords' : IDL.Func([], [IDL.Vec(BorrowRecord)], ['query']),
  'getRecommendations' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Recommendation)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkPrincipalToMember' : IDL.Func([IDL.Nat], [], []),
  'removeBook' : IDL.Func([IDL.Nat], [], []),
  'removeMember' : IDL.Func([IDL.Nat], [], []),
  'returnBook' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchBooksByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'searchBooksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'searchBooksByISBN' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'searchBooksByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'updateBook' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateMember' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'faculty' : IDL.Null,
          'student' : IDL.Null,
          'external' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BorrowRecord = IDL.Record({
    'id' : IDL.Nat,
    'memberId' : IDL.Nat,
    'borrowDate' : Time,
    'fineAmount' : IDL.Nat,
    'dueDate' : Time,
    'bookId' : IDL.Nat,
    'returnDate' : IDL.Opt(Time),
  });
  const Book = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'availableQuantity' : IDL.Nat,
    'isbn' : IDL.Text,
    'yearPublished' : IDL.Nat,
    'author' : IDL.Text,
    'genre' : IDL.Text,
    'totalQuantity' : IDL.Nat,
  });
  const Member = IDL.Record({
    'id' : IDL.Nat,
    'joinDate' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'memberType' : IDL.Variant({
      'faculty' : IDL.Null,
      'student' : IDL.Null,
      'external' : IDL.Null,
    }),
  });
  const UserProfile = IDL.Record({
    'memberId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalFines' : IDL.Nat,
    'overdueLoans' : IDL.Nat,
    'mostBorrowedBooks' : IDL.Vec(Book),
    'totalBooks' : IDL.Nat,
    'totalMembers' : IDL.Nat,
    'recentlyAddedBooks' : IDL.Vec(Book),
    'activeLoans' : IDL.Nat,
  });
  const Recommendation = IDL.Record({
    'title' : IDL.Text,
    'genreScore' : IDL.Nat,
    'bookId' : IDL.Nat,
    'author' : IDL.Text,
    'genre' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addMember' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'faculty' : IDL.Null,
            'student' : IDL.Null,
            'external' : IDL.Null,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'borrowBook' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'calculateFine' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getActiveBorrowRecords' : IDL.Func([], [IDL.Vec(BorrowRecord)], ['query']),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getBookBorrowHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BorrowRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMemberBorrowHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BorrowRecord)],
        ['query'],
      ),
    'getOverdueBorrowRecords' : IDL.Func(
        [],
        [IDL.Vec(BorrowRecord)],
        ['query'],
      ),
    'getRecommendations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Recommendation)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkPrincipalToMember' : IDL.Func([IDL.Nat], [], []),
    'removeBook' : IDL.Func([IDL.Nat], [], []),
    'removeMember' : IDL.Func([IDL.Nat], [], []),
    'returnBook' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchBooksByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'searchBooksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'searchBooksByISBN' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'searchBooksByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'updateBook' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateMember' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'faculty' : IDL.Null,
            'student' : IDL.Null,
            'external' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };